default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || "screenshot_verification_dev" %>

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] || "screenshot_verification_test" %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: <%= ENV["DATABASE_NAME_PROD"] %>
