require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reference_images", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ReferenceImage. As you add validations to ReferenceImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ReferenceImage.create! valid_attributes
      get reference_images_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      reference_image = ReferenceImage.create! valid_attributes
      get reference_image_url(reference_image)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_reference_image_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      reference_image = ReferenceImage.create! valid_attributes
      get edit_reference_image_url(reference_image)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReferenceImage" do
        expect {
          post reference_images_url, params: { reference_image: valid_attributes }
        }.to change(ReferenceImage, :count).by(1)
      end

      it "redirects to the created reference_image" do
        post reference_images_url, params: { reference_image: valid_attributes }
        expect(response).to redirect_to(reference_image_url(ReferenceImage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReferenceImage" do
        expect {
          post reference_images_url, params: { reference_image: invalid_attributes }
        }.to change(ReferenceImage, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post reference_images_url, params: { reference_image: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reference_image" do
        reference_image = ReferenceImage.create! valid_attributes
        patch reference_image_url(reference_image), params: { reference_image: new_attributes }
        reference_image.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the reference_image" do
        reference_image = ReferenceImage.create! valid_attributes
        patch reference_image_url(reference_image), params: { reference_image: new_attributes }
        reference_image.reload
        expect(response).to redirect_to(reference_image_url(reference_image))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        reference_image = ReferenceImage.create! valid_attributes
        patch reference_image_url(reference_image), params: { reference_image: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested reference_image" do
      reference_image = ReferenceImage.create! valid_attributes
      expect {
        delete reference_image_url(reference_image)
      }.to change(ReferenceImage, :count).by(-1)
    end

    it "redirects to the reference_images list" do
      reference_image = ReferenceImage.create! valid_attributes
      delete reference_image_url(reference_image)
      expect(response).to redirect_to(reference_images_url)
    end
  end
end
